#!/usr/bin/env bash
# ebgp-session — interactive lab CLI (generated by xForm semantic-lab-fw)
#
# Usage:
#   ./lab.sh              # start a lab-aware bash subshell
#   source lab.sh         # load helpers into the current shell
#
# Then:
#   dut                   # interactive vtysh on dut
#   dut show bgp summary  # one-shot vtysh command
#   dut shell             # bash inside the container
#   nodes / status        # list nodes / containerlab inspect
#   Tab-complete node names and common vtysh verbs

# If executed (not sourced), open a dedicated interactive bash with this rcfile.
if [[ "${BASH_SOURCE[0]-}" == "${0}" ]]; then
  exec bash --rcfile "${BASH_SOURCE[0]}"
fi

_LAB_NAME="ebgp-session"
_LAB_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
_LAB_TOPOLOGY="${_LAB_DIR}/clab.yml"
_LAB_NODES=(dut x1 x2 )

# Avoid re-defining helpers if sourced twice.
if [[ -n "${_LAB_CLI_LOADED:-}" ]]; then
  return 0 2>/dev/null || true
fi
_LAB_CLI_LOADED=1

_lab_docker_tty() {
  if [[ -t 0 && -t 1 ]]; then
    printf '%s' "-it"
  else
    printf '%s' "-i"
  fi
}

_lab_vtysh() {
  local node=${1:?node required}
  shift
  local tty
  tty="$(_lab_docker_tty)"
  # shellcheck disable=SC2086
  if [[ $# -eq 0 ]]; then
    docker exec ${tty} "$node" vtysh
  elif [[ $1 == shell || $1 == bash ]]; then
    shift
    docker exec ${tty} "$node" bash -il "$@"
  elif [[ $1 == -c ]]; then
    docker exec ${tty} "$node" vtysh "$@"
  else
    docker exec ${tty} "$node" vtysh -c "$*"
  fi
}

dut() { _lab_vtysh "dut" "$@"; }
x1() { _lab_vtysh "x1" "$@"; }
x2() { _lab_vtysh "x2" "$@"; }

nodes() {
  printf '%s\n' "${_LAB_NODES[@]}"
}

status() {
  if command -v containerlab >/dev/null 2>&1; then
    containerlab inspect -t "${_LAB_TOPOLOGY}"
  else
    local node
    for node in "${_LAB_NODES[@]}"; do
      docker ps --filter "name=^${node}$"
    done
  fi
}

_lab_complete_node_cmds() {
  local cur=${COMP_WORDS[COMP_CWORD]}
  local verbs="show configure write shell bash -c"
  if [[ ${COMP_CWORD} -eq 1 ]]; then
    COMPREPLY=($(compgen -W "${verbs}" -- "${cur}"))
  else
    COMPREPLY=()
  fi
}

complete -o default -F _lab_complete_node_cmds dut
complete -o default -F _lab_complete_node_cmds x1
complete -o default -F _lab_complete_node_cmds x2

# Friendly prompt while this environment is active.
PS1="(${_LAB_NAME}) \[\e[1;32m\]\u@\h\[\e[0m\]:\[\e[1;34m\]\w\[\e[0m\]\$ "
export PS1

cat <<EOF
Lab ${_LAB_NAME} CLI ready (nodes: ${_LAB_NODES[*]})
  <node>                  interactive vtysh
  <node> show …           one-shot vtysh command
  <node> shell            bash in container
  nodes | status          list nodes / lab status
EOF
