#!/usr/bin/env bash
# fabric-from-image — interactive lab CLI (generated by xForm semantic-lab-fw)
#
# Usage:
#   ./lab.sh              # start a lab-aware bash subshell
#   source lab.sh         # load helpers into the current shell
#
# Then:
#   dut                   # interactive device CLI on dut (vtysh / birdcl)
#   dut show bgp summary  # one-shot CLI command
#   dut shell             # bash inside the container
#   nodes / status / web          list nodes, inspect, web UI
#   stop / restart / destroy / reconfigure   containerlab lifecycle
#   Tab-complete node names and common CLI verbs

# If executed (not sourced), open a dedicated interactive bash with this rcfile.
if [[ "${BASH_SOURCE[0]-}" == "${0}" ]]; then
  exec bash --rcfile "${BASH_SOURCE[0]}"
fi

_LAB_NAME="fabric-from-image"
_LAB_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
_LAB_TOPOLOGY="${_LAB_DIR}/clab.yml"
_LAB_WEB_DIR=""
if [[ -d "${_LAB_DIR}/../web" ]]; then
  _LAB_WEB_DIR="$(cd "${_LAB_DIR}/../web" && pwd)"
fi
_LAB_NODES=(client1 client2 L1-1-1 L1-1-2 L1-2-1 L1-3-1 L1-3-2 L1-4-1 L2-1-1 L2-1-2 L2-2-1 L2-3-1 L2-4-1 S1-1 S1-2 S1-3 S1-4 S2-1 S2-2 S2-3 S2-4 SS1 SS2 SS3 SS4 SS5 SS6 )
_LAB_WEB_PORT="${LAB_WEB_PORT:-42042}"
_LAB_WEB_IMAGE="${LAB_WEB_IMAGE:-xform:local}"
_LAB_WEB_CONTAINER="lab-web"

# Avoid re-defining helpers if sourced twice.
if [[ -n "${_LAB_CLI_LOADED:-}" ]]; then
  return 0 2>/dev/null || true
fi
_LAB_CLI_LOADED=1

# Per-node interactive CLI binary (device template #cli.interactive).
# VPP runs the control plane in the dataplane netns — set _LAB_NETNS_<node>.
# OS shell comes from #cli.shell (Alpine has no bash).
_LAB_CLI_client1=sh
_LAB_SHELL_client1=sh
_LAB_CLI_client2=sh
_LAB_SHELL_client2=sh
_LAB_CLI_L1-1-1=vtysh
_LAB_SHELL_L1-1-1=bash
_LAB_CLI_L1-1-2=vtysh
_LAB_SHELL_L1-1-2=bash
_LAB_CLI_L1-2-1=vtysh
_LAB_SHELL_L1-2-1=bash
_LAB_CLI_L1-3-1=vtysh
_LAB_SHELL_L1-3-1=bash
_LAB_CLI_L1-3-2=vtysh
_LAB_SHELL_L1-3-2=bash
_LAB_CLI_L1-4-1=vtysh
_LAB_SHELL_L1-4-1=bash
_LAB_CLI_L2-1-1=vtysh
_LAB_SHELL_L2-1-1=bash
_LAB_CLI_L2-1-2=vtysh
_LAB_SHELL_L2-1-2=bash
_LAB_CLI_L2-2-1=vtysh
_LAB_SHELL_L2-2-1=bash
_LAB_CLI_L2-3-1=vtysh
_LAB_SHELL_L2-3-1=bash
_LAB_CLI_L2-4-1=vtysh
_LAB_SHELL_L2-4-1=bash
_LAB_CLI_S1-1=vtysh
_LAB_SHELL_S1-1=bash
_LAB_CLI_S1-2=vtysh
_LAB_SHELL_S1-2=bash
_LAB_CLI_S1-3=vtysh
_LAB_SHELL_S1-3=bash
_LAB_CLI_S1-4=vtysh
_LAB_SHELL_S1-4=bash
_LAB_CLI_S2-1=vtysh
_LAB_SHELL_S2-1=bash
_LAB_CLI_S2-2=vtysh
_LAB_SHELL_S2-2=bash
_LAB_CLI_S2-3=vtysh
_LAB_SHELL_S2-3=bash
_LAB_CLI_S2-4=vtysh
_LAB_SHELL_S2-4=bash
_LAB_CLI_SS1=vtysh
_LAB_SHELL_SS1=bash
_LAB_CLI_SS2=vtysh
_LAB_SHELL_SS2=bash
_LAB_CLI_SS3=vtysh
_LAB_SHELL_SS3=bash
_LAB_CLI_SS4=vtysh
_LAB_SHELL_SS4=bash
_LAB_CLI_SS5=vtysh
_LAB_SHELL_SS5=bash
_LAB_CLI_SS6=vtysh
_LAB_SHELL_SS6=bash

_lab_cli() {
  local node=${1:?node required}
  local cli_var="_LAB_CLI_${node}"
  local netns_var="_LAB_NETNS_${node}"
  local shell_var="_LAB_SHELL_${node}"
  local cli="${!cli_var:-vtysh}"
  local netns="${!netns_var:-}"
  local shell="${!shell_var:-sh}"
  shift
  if [[ $# -eq 0 ]]; then
    # Interactive device CLI — always allocate a TTY for job control / line editing.
    if [[ -n "$netns" ]]; then
      docker exec -it "$node" ip netns exec "$netns" "$cli"
    else
      docker exec -it "$node" "$cli"
    fi
  elif [[ $1 == shell || $1 == bash ]]; then
    shift
    docker exec -it "$node" "$shell" -i "$@"
  elif [[ $1 == -c ]]; then
    if [[ -n "$netns" ]]; then
      if [[ "$cli" == "vtysh" ]]; then
        docker exec -i "$node" ip netns exec "$netns" vtysh "$@"
      else
        shift
        docker exec -i "$node" ip netns exec "$netns" "$cli" "$@"
      fi
    elif [[ "$cli" == "vtysh" ]]; then
      docker exec -i "$node" vtysh "$@"
    else
      shift
      docker exec -i "$node" "$cli" "$@"
    fi
  else
    if [[ -n "$netns" ]]; then
      if [[ "$cli" == "vtysh" ]]; then
        docker exec -i "$node" ip netns exec "$netns" vtysh -c "$*"
      else
        docker exec -i "$node" ip netns exec "$netns" "$cli" "$@"
      fi
    elif [[ "$cli" == "vtysh" ]]; then
      docker exec -i "$node" vtysh -c "$*"
    else
      docker exec -i "$node" "$cli" "$@"
    fi
  fi
}

client1() { _lab_cli "client1" "$@"; }
client2() { _lab_cli "client2" "$@"; }
L1-1-1() { _lab_cli "L1-1-1" "$@"; }
L1-1-2() { _lab_cli "L1-1-2" "$@"; }
L1-2-1() { _lab_cli "L1-2-1" "$@"; }
L1-3-1() { _lab_cli "L1-3-1" "$@"; }
L1-3-2() { _lab_cli "L1-3-2" "$@"; }
L1-4-1() { _lab_cli "L1-4-1" "$@"; }
L2-1-1() { _lab_cli "L2-1-1" "$@"; }
L2-1-2() { _lab_cli "L2-1-2" "$@"; }
L2-2-1() { _lab_cli "L2-2-1" "$@"; }
L2-3-1() { _lab_cli "L2-3-1" "$@"; }
L2-4-1() { _lab_cli "L2-4-1" "$@"; }
S1-1() { _lab_cli "S1-1" "$@"; }
S1-2() { _lab_cli "S1-2" "$@"; }
S1-3() { _lab_cli "S1-3" "$@"; }
S1-4() { _lab_cli "S1-4" "$@"; }
S2-1() { _lab_cli "S2-1" "$@"; }
S2-2() { _lab_cli "S2-2" "$@"; }
S2-3() { _lab_cli "S2-3" "$@"; }
S2-4() { _lab_cli "S2-4" "$@"; }
SS1() { _lab_cli "SS1" "$@"; }
SS2() { _lab_cli "SS2" "$@"; }
SS3() { _lab_cli "SS3" "$@"; }
SS4() { _lab_cli "SS4" "$@"; }
SS5() { _lab_cli "SS5" "$@"; }
SS6() { _lab_cli "SS6" "$@"; }

nodes() {
  printf '%s\n' "${_LAB_NODES[@]}"
}

status() {
  if command -v containerlab >/dev/null 2>&1; then
    containerlab inspect -t "${_LAB_TOPOLOGY}"
  else
    local node
    for node in "${_LAB_NODES[@]}"; do
      docker ps --filter "name=^${node}$"
    done
  fi
}

_lab_require_clab() {
  if ! command -v containerlab >/dev/null 2>&1; then
    echo "containerlab not found; cannot manage ${_LAB_TOPOLOGY}" >&2
    return 1
  fi
}

# Optional node list → comma-separated --node-filter value.
_lab_clab_node_filter() {
  local IFS=,
  printf '%s' "$*"
}

stop() {
  _lab_require_clab || return 1
  if [[ $# -eq 0 ]]; then
    containerlab stop -t "${_LAB_TOPOLOGY}"
  else
    local -a flags=()
    local n
    for n in "$@"; do flags+=(-n "$n"); done
    containerlab stop -t "${_LAB_TOPOLOGY}" "${flags[@]}"
  fi
}

restart() {
  _lab_require_clab || return 1
  if [[ $# -eq 0 ]]; then
    containerlab restart -t "${_LAB_TOPOLOGY}"
  else
    local -a flags=()
    local n
    for n in "$@"; do flags+=(-n "$n"); done
    containerlab restart -t "${_LAB_TOPOLOGY}" "${flags[@]}"
  fi
}

destroy() {
  _lab_require_clab || return 1
  if [[ $# -eq 0 ]]; then
    echo "Destroying lab ${_LAB_NAME} (${_LAB_TOPOLOGY})…"
    containerlab destroy -t "${_LAB_TOPOLOGY}"
  else
    local filter
    filter="$(_lab_clab_node_filter "$@")"
    echo "Destroying node(s) ${filter} in ${_LAB_NAME}…"
    containerlab destroy -t "${_LAB_TOPOLOGY}" --node-filter "${filter}"
  fi
}

reconfigure() {
  _lab_require_clab || return 1
  if [[ $# -eq 0 ]]; then
    echo "Reconfiguring lab ${_LAB_NAME} (${_LAB_TOPOLOGY})…"
    containerlab deploy -t "${_LAB_TOPOLOGY}" --reconfigure
  else
    local filter
    filter="$(_lab_clab_node_filter "$@")"
    echo "Reconfiguring node(s) ${filter} in ${_LAB_NAME}…"
    containerlab deploy -t "${_LAB_TOPOLOGY}" --reconfigure --node-filter "${filter}"
  fi
}

# Back-compat alias for full-lab destroy.
down() { destroy "$@"; }

_lab_open_web() {
  local url="http://127.0.0.1:${_LAB_WEB_PORT}/"
  echo "Lab web UI → ${url}"
  if command -v xdg-open >/dev/null 2>&1; then
    (sleep 0.3 && xdg-open "${url}") >/dev/null 2>&1 &
  elif command -v open >/dev/null 2>&1; then
    (sleep 0.3 && open "${url}") >/dev/null 2>&1 &
  fi
}

_lab_web_running() {
  docker ps --format '{{.Names}}' 2>/dev/null | grep -qx "${_LAB_WEB_CONTAINER}"
}

web() {
  # Outer xForm controller (xform:local) owns the UI — open it if already listening.
  if curl -fsS "http://127.0.0.1:${_LAB_WEB_PORT}/api/session" >/dev/null 2>&1; then
    _lab_open_web
    return 0
  fi

  # Legacy: lab-web node still present in an older topology.
  if _lab_web_running; then
    _lab_open_web
    return 0
  fi

  echo "xForm controller not running on 127.0.0.1:${_LAB_WEB_PORT}" >&2
  echo "  docker build -t xform:local <xform-root>" >&2
  echo "  docker run --rm --privileged \\
    -p 127.0.0.1:${_LAB_WEB_PORT}:${_LAB_WEB_PORT} \\
    xform:local" >&2
  return 1
}

_lab_complete_node_cmds() {
  local cur=${COMP_WORDS[COMP_CWORD]}
  local verbs="show configure write shell bash -c"
  if [[ ${COMP_CWORD} -eq 1 ]]; then
    COMPREPLY=($(compgen -W "${verbs}" -- "${cur}"))
  else
    COMPREPLY=()
  fi
}

complete -o default -F _lab_complete_node_cmds client1
complete -o default -F _lab_complete_node_cmds client2
complete -o default -F _lab_complete_node_cmds L1-1-1
complete -o default -F _lab_complete_node_cmds L1-1-2
complete -o default -F _lab_complete_node_cmds L1-2-1
complete -o default -F _lab_complete_node_cmds L1-3-1
complete -o default -F _lab_complete_node_cmds L1-3-2
complete -o default -F _lab_complete_node_cmds L1-4-1
complete -o default -F _lab_complete_node_cmds L2-1-1
complete -o default -F _lab_complete_node_cmds L2-1-2
complete -o default -F _lab_complete_node_cmds L2-2-1
complete -o default -F _lab_complete_node_cmds L2-3-1
complete -o default -F _lab_complete_node_cmds L2-4-1
complete -o default -F _lab_complete_node_cmds S1-1
complete -o default -F _lab_complete_node_cmds S1-2
complete -o default -F _lab_complete_node_cmds S1-3
complete -o default -F _lab_complete_node_cmds S1-4
complete -o default -F _lab_complete_node_cmds S2-1
complete -o default -F _lab_complete_node_cmds S2-2
complete -o default -F _lab_complete_node_cmds S2-3
complete -o default -F _lab_complete_node_cmds S2-4
complete -o default -F _lab_complete_node_cmds SS1
complete -o default -F _lab_complete_node_cmds SS2
complete -o default -F _lab_complete_node_cmds SS3
complete -o default -F _lab_complete_node_cmds SS4
complete -o default -F _lab_complete_node_cmds SS5
complete -o default -F _lab_complete_node_cmds SS6

# Friendly prompt while this environment is active.
PS1="(${_LAB_NAME}) \[\e[1;32m\]\u@\h\[\e[0m\]:\[\e[1;34m\]\w\[\e[0m\]\$ "
export PS1

cat <<EOF
Lab ${_LAB_NAME} CLI ready (nodes: ${_LAB_NODES[*]})
  <node>                  interactive device CLI (vtysh / birdcl / netns)
  <node> show …           one-shot CLI command
  <node> shell            bash in container
  nodes | status | web    list nodes / inspect / browser terminal UI
  Containerlab:
    stop [node…]          park dataplane and stop (all if omitted)
    restart [node…]       seamless restart (reattaches dataplane)
    destroy [node…]       remove node(s), or whole lab if omitted
    reconfigure [node…]   deploy --reconfigure [--node-filter]
EOF
