#!/bin/sh
# client1 — initialize (generated by xForm semantic-lab-fw)
set -e
#
# Forwarding (harmless on hosts)
#
sysctl -w net.ipv4.ip_forward=1 >/dev/null
# L4 multipath hash (VXLAN module overrides to 2 when present).
sysctl -w net.ipv4.fib_multipath_hash_policy=1 >/dev/null
#
# iproute2 provides `ip monitor` (BusyBox ip does not)
#
apk add --no-cache iproute2 >/dev/null
#
# One-shot module setup (packages, etc.) — not re-run on link events
#

#
# Validation plugin packages
#
apk add --no-cache iperf3 >/dev/null
#
# Validation plugin binaries (staged by docker.build into config/bin)
# libcap: setcap CAP_NET_RAW so dublin-traceroute (etc.) need not run as root
#
apk add --no-cache libcap util-linux >/dev/null
mkdir -p /usr/local/bin
cp /opt/lab-config/bin/dublin-traceroute /usr/local/bin/dublin-traceroute
chmod +x /usr/local/bin/dublin-traceroute
# docker cp / cp drop file capabilities — re-apply after install
setcap cap_net_raw+ep /usr/local/bin/dublin-traceroute

#
# Wait for Containerlab data-plane interfaces once (skip virtual SVI / vlan_member).
# Clab wires veths after start — wait long enough to avoid a crash-loop that
# permanently drops peer endpoints.
#
WAIT_IFACE_TIMEOUT="${CLAB_IFACE_WAIT:-60}"
timeout "$WAIT_IFACE_TIMEOUT" sh -c 'until [ -e /sys/class/net/eth1 ]; do sleep 0.2; done' \
  || { echo "interface eth1 not present within ${WAIT_IFACE_TIMEOUT}s" >&2; exit 1; }
#
# Dataplane modules (#initialize) ordered by dataplane before/after — before addressing
#
#
# Re-apply addresses / MTU after peer swap (veth recreate), then non-dataplane
# module hooks (routing static routes, …). Kernel drops routes when the iface
# goes down — address restore alone is not enough after a neighbor swap.
#
_DATAPLANE_IGNORE_FILE=/run/dataplane-ignore-until
dataplane_ignore() {
  echo $(( $(date +%s) + ${1:-3} )) >"$_DATAPLANE_IGNORE_FILE"
}
dataplane_ignoring() {
  _now=$(date +%s)
  _until=$(cat "$_DATAPLANE_IGNORE_FILE" 2>/dev/null || echo 0)
  [ "$_now" -lt "$_until" ]
}
_iface_admin_up() {
  ip -br link show dev "$1" 2>/dev/null | grep -q ' UP '
}
apply_dataplane_iface() {
  _if="$1"
  [ -n "$_if" ] || return 0
  [ -e "/sys/class/net/$_if" ] || return 0
  case "$_if" in
    eth1)
      _cur=$(sysctl -n net.ipv6.conf.eth1.disable_ipv6 2>/dev/null || echo "")
      [ "$_cur" = "1" ] || sysctl -qw net.ipv6.conf.eth1.disable_ipv6=1 2>/dev/null || true
      _iface_admin_up eth1 || ip link set eth1 up
      ip addr replace 10.10.0.26/24 dev eth1
      ;;
    *) return 0 ;;
  esac
}

apply_dataplane() {
  if [ "$#" -ge 1 ] && [ -n "$1" ]; then
    apply_dataplane_iface "$1"
  else
    apply_dataplane_iface "eth1"
  fi

ip route replace 0.0.0.0/0 via 10.10.0.15


  dataplane_ignore 3
}

apply_dataplane
#
# Keep the container running; re-apply when data-plane links return to UP
# (Containerlab apply / device swap recreates neighbor veths).
#
dataplane_ignore 5
ip -o monitor link | while IFS= read -r line; do
  case "$line" in
    Deleted\ *) continue ;;
  esac
  dataplane_ignoring && continue
  case "$line" in
    *" eth1@"*|*" eth1:"*)
      case "$line" in
        *state\ UP*)
          sleep 0.2
          apply_dataplane "eth1" || true
          ;;
      esac
      ;;
  esac
done
