#!/bin/bash
# L2-1-1 — initialize (generated by xForm semantic-lab-fw)
set -e
set -x
#
# Shared config/ bind → daemon conf path (see #clab). `do write` persists via symlink.
#
_LAB_CFG=/opt/lab-config/L2-1-1.conf
if [ -f "$_LAB_CFG" ]; then
  mkdir -p "$(dirname "/etc/frr/frr.conf")"
  rm -f "/etc/frr/frr.conf"
  ln -sfn "$_LAB_CFG" "/etc/frr/frr.conf"
fi
#
# Create bash profile script
#
cat <<'SCRIPT' >/root/.bash_profile
#!/bin/bash
#
export PS1="\h(bash)# "
echo
echo "Use vtysh to connect to FRR daemon"
echo
SCRIPT
#
# Forwarding (only for address families enabled on this node)
#
sysctl -w net.ipv4.ip_forward=1
# L4 multipath hash so underlay ECMP (e.g. dublin-traceroute) diversifies by port.
# VXLAN module overrides to 2 (inner L3 / overlay) when present.
sysctl -w net.ipv4.fib_multipath_hash_policy=1
sysctl -w net.ipv6.conf.all.forwarding=1
#
# Management VRF — move eth0 into mgmt so data-plane routing stays separate
#
if grep vrf /proc/modules && ip link show dev eth0; then
  def_nh=$(ip route list default|awk '{ print $3 }')
  if [ ! -e /sys/devices/virtual/net/mgmt ]; then
    ip link add mgmt type vrf table 42
  fi
  ip link set mgmt up
  sysctl -qw net.ipv6.conf.eth0.keep_addr_on_down=1
  ip link set eth0 master mgmt
  if [[ -n "$def_nh" ]]; then
    ip route add 0.0.0.0/0 vrf mgmt via $def_nh
  fi
fi
#
# Send ARP requests from a sane source IP address
#
sysctl -w net.ipv4.conf.all.arp_announce=2
#
# Create missing loopback/stub as dummy (do NOT create ethN — Containerlab attaches those)
#
#
# Wait for Containerlab data-plane interfaces before sysctl / addressing
# (skip virtual SVI / vlan_member — module initialize creates those).
# Clab wires veths after containers start; keep this well above deploy lag so
# a miss does not crash-loop and permanently drop peer endpoints.
#
WAIT_IFACE_TIMEOUT="${CLAB_IFACE_WAIT:-60}"
timeout "$WAIT_IFACE_TIMEOUT" sh -c 'until [ -e /sys/class/net/eth1 ]; do sleep 0.2; done' \
  || { echo "interface eth1 not present within ${WAIT_IFACE_TIMEOUT}s" >&2; exit 1; }
timeout "$WAIT_IFACE_TIMEOUT" sh -c 'until [ -e /sys/class/net/eth2 ]; do sleep 0.2; done' \
  || { echo "interface eth2 not present within ${WAIT_IFACE_TIMEOUT}s" >&2; exit 1; }
timeout "$WAIT_IFACE_TIMEOUT" sh -c 'until [ -e /sys/class/net/eth3 ]; do sleep 0.2; done' \
  || { echo "interface eth3 not present within ${WAIT_IFACE_TIMEOUT}s" >&2; exit 1; }
timeout "$WAIT_IFACE_TIMEOUT" sh -c 'until [ -e /sys/class/net/eth4 ]; do sleep 0.2; done' \
  || { echo "interface eth4 not present within ${WAIT_IFACE_TIMEOUT}s" >&2; exit 1; }
#
# Dataplane modules (#initialize) ordered by dataplane before/after — before addressing
#
#
# Linux interface sysctl.
# Boot path may bring links up once. The link monitor (#monitor) only restores
# LLA sysctls on hotplug — never `ip link set` (that re-enters netlink and
# flaps BGP unnumbered across the fabric during convergence).
#
_DATAPLANE_IGNORE_FILE=/run/dataplane-ignore-until
dataplane_ignore() {
  echo $(( $(date +%s) + ${1:-3} )) >"$_DATAPLANE_IGNORE_FILE"
}
dataplane_ignoring() {
  _now=$(date +%s)
  _until=$(cat "$_DATAPLANE_IGNORE_FILE" 2>/dev/null || echo 0)
  [ "$_now" -lt "$_until" ]
}
_sysctl_set() {
  # Avoid rewriting an identical value (some sysctls flap the iface).
  _path="$1"
  _want="$2"
  _cur=$(sysctl -n "$_path" 2>/dev/null || echo "")
  [ "$_cur" = "$_want" ] || sysctl -qw "$_path=$_want"
}
_iface_admin_up() {
  # Prefer brief output — flag order varies (`<UP,…>` vs `<BROADCAST,…,UP,…>`).
  ip -br link show dev "$1" 2>/dev/null | grep -q ' UP '
}
# Hotplug-only: LLA sysctls. No-op when already correct (no netlink noise).
restore_dataplane_sysctl() {
  _if="$1"
  [ -n "$_if" ] || return 0
  [ -e "/sys/class/net/$_if" ] || return 0
  case "$_if" in
    eth1)
      _sysctl_set net/ipv6/conf/eth1/keep_addr_on_down 1
      _sysctl_set net/ipv6/conf/eth1/autoconf 0
      _sysctl_set net/ipv6/conf/eth1/accept_ra 0
      _sysctl_set net/ipv6/conf/eth1/addr_gen_mode 3
      ;;
    eth2)
      _sysctl_set net/ipv6/conf/eth2/keep_addr_on_down 1
      _sysctl_set net/ipv6/conf/eth2/autoconf 0
      _sysctl_set net/ipv6/conf/eth2/accept_ra 0
      _sysctl_set net/ipv6/conf/eth2/addr_gen_mode 3
      ;;
    eth3)
      _sysctl_set net/ipv6/conf/eth3/keep_addr_on_down 1
      _sysctl_set net/ipv6/conf/eth3/autoconf 0
      _sysctl_set net/ipv6/conf/eth3/accept_ra 0
      _sysctl_set net/ipv6/conf/eth3/addr_gen_mode 3
      ;;
    eth4)
      _sysctl_set net/ipv6/conf/eth4/keep_addr_on_down 1
      _sysctl_set net/ipv6/conf/eth4/autoconf 0
      _sysctl_set net/ipv6/conf/eth4/accept_ra 0
      _sysctl_set net/ipv6/conf/eth4/addr_gen_mode 3
      ;;
    *) return 0 ;;
  esac
}
apply_dataplane_iface() {
  _if="$1"
  [ -n "$_if" ] || return 0
  [ -e "/sys/class/net/$_if" ] || return 0
  case "$_if" in
    eth1)
      _sysctl_set net/ipv6/conf/eth1/keep_addr_on_down 1
      _sysctl_set net/ipv6/conf/eth1/autoconf 0
      _sysctl_set net/ipv6/conf/eth1/accept_ra 0
      _sysctl_set net/ipv6/conf/eth1/addr_gen_mode 3
      _iface_admin_up eth1 || ip link set eth1 up
      ;;
    eth2)
      _sysctl_set net/ipv6/conf/eth2/keep_addr_on_down 1
      _sysctl_set net/ipv6/conf/eth2/autoconf 0
      _sysctl_set net/ipv6/conf/eth2/accept_ra 0
      _sysctl_set net/ipv6/conf/eth2/addr_gen_mode 3
      _iface_admin_up eth2 || ip link set eth2 up
      ;;
    eth3)
      _sysctl_set net/ipv6/conf/eth3/keep_addr_on_down 1
      _sysctl_set net/ipv6/conf/eth3/autoconf 0
      _sysctl_set net/ipv6/conf/eth3/accept_ra 0
      _sysctl_set net/ipv6/conf/eth3/addr_gen_mode 3
      _iface_admin_up eth3 || ip link set eth3 up
      ;;
    eth4)
      _sysctl_set net/ipv6/conf/eth4/keep_addr_on_down 1
      _sysctl_set net/ipv6/conf/eth4/autoconf 0
      _sysctl_set net/ipv6/conf/eth4/accept_ra 0
      _sysctl_set net/ipv6/conf/eth4/addr_gen_mode 3
      _iface_admin_up eth4 || ip link set eth4 up
      ;;
    *) return 0 ;;
  esac
}

apply_dataplane_ifaces() {
  if [ "$#" -ge 1 ] && [ -n "$1" ]; then
    apply_dataplane_iface "$1"
  else
    apply_dataplane_iface "eth1"
    apply_dataplane_iface "eth2"
    apply_dataplane_iface "eth3"
    apply_dataplane_iface "eth4"
  fi
  dataplane_ignore 3
}

apply_dataplane_ifaces
#
# FRR daemons — baseline all optional daemons off; modules enable what they need
#
cat >/etc/frr/daemons <<'DAEMONS'
# Generated by xForm semantic-lab-fw (Netlab-style FRR daemons)
bgpd=no
ospfd=no
ospf6d=no
ripd=no
ripngd=no
isisd=no
pimd=no
ldpd=no
nhrpd=no
eigrpd=no
babeld=no
sharpd=no
pbrd=no
bfdd=no
fabricd=no
vrrpd=no
pathd=no
vtysh_enable=yes
zebra_options="  -A 127.0.0.1 -s 90000000"
bgpd_options="   -A 127.0.0.1"
ospfd_options="  -A 127.0.0.1"
ospf6d_options=" -A ::1"
ripd_options="   -A 127.0.0.1"
ripngd_options=" -A ::1"
isisd_options="  -A 127.0.0.1"
pimd_options="   -A 127.0.0.1"
ldpd_options="   -A 127.0.0.1"
nhrpd_options="  -A 127.0.0.1"
eigrpd_options=" -A 127.0.0.1"
babeld_options=" -A 127.0.0.1"
sharpd_options=" -A 127.0.0.1"
pbrd_options="   -A 127.0.0.1"
staticd_options="-A 127.0.0.1"
bfdd_options="   -A 127.0.0.1"
fabricd_options="-A 127.0.0.1"
vrrpd_options="  -A 127.0.0.1"
pathd_options="  -A 127.0.0.1"
frr_profile="datacenter"
bgpd=yes
DAEMONS
#
# vtysh + log directory
#
echo "service integrated-vtysh-config" >/etc/frr/vtysh.conf
mkdir -p /var/log/frr && chown frr:frr /var/log/frr
#
# Initial FRR config applied via vtysh after daemons are up
#
cat >/tmp/config <<'CONFIG'
hostname L2-1-1
!
log file /var/log/frr/frr.log informational
!
ip forwarding
ipv6 forwarding
!
vrf mgmt
 exit-vrf
!
frr defaults datacenter
!
interface lo
 no shutdown
 ip address 172.16.0.21/32
!
interface eth1
 no shutdown
!
interface eth2
 no shutdown
!
interface eth3
 no shutdown
!
interface eth4
 no shutdown
!
!
router bgp 65311
  no bgp ebgp-requires-policy
  no bgp default ipv4-unicast
  bgp default show-hostname
  bgp bestpath as-path multipath-relax
  bgp router-id 172.16.0.21
!
  neighbor eth1 interface remote-as 65000
  neighbor eth1 description S2-1
!
  neighbor eth2 interface remote-as 65000
  neighbor eth2 description S2-2
!
  neighbor eth3 interface remote-as 65000
  neighbor eth3 description S2-3
!
  neighbor eth4 interface remote-as 65000
  neighbor eth4 description S2-4
!
 address-family ipv4 unicast
  maximum-paths 64
  maximum-paths ibgp 64
!
  network 172.16.0.21/32
!
  neighbor eth1 activate
!
  neighbor eth2 activate
!
  neighbor eth3 activate
!
  neighbor eth4 activate
!
 exit-address-family
 address-family ipv6 unicast
  maximum-paths 64
  maximum-paths ibgp 64
!
!
  neighbor eth1 activate
!
  neighbor eth2 activate
!
  neighbor eth3 activate
!
  neighbor eth4 activate
!
 exit-address-family
!
do write
CONFIG
#
# Start FRR (reads /etc/frr/daemons), wait until watchfrr reports ready,
# then apply initial config. A fixed sleep races device-swap reconnects.
#
/usr/lib/frr/docker-start &
for _ in $(seq 1 60); do
  [ -f /var/run/frr/watchfrr.started ] && break
  sleep 0.25
done
if [ ! -f /var/run/frr/watchfrr.started ]; then
  echo "FRR daemons failed to start (no watchfrr.started)" >&2
  exit 1
fi
# VTY sockets lag the started flag slightly — require a real zebra answer
for _ in $(seq 1 40); do
  _out=$(vtysh -c "show ip route" 2>&1 || true)
  case "$_out" in
    *"zebra is not running"*|"") ;;
    *) break ;;
  esac
  sleep 0.25
done
vtysh -f /tmp/config
# Start link watcher only after zebra config — avoids no-shutdown stampede.
dataplane_ignore 5
(
  ip -o monitor link | while IFS= read -r line; do
    case "$line" in
      Deleted\ *) continue ;;
    esac
    dataplane_ignoring && continue
    case "$line" in
      *" eth1@"*|*" eth1:"*)
        case "$line" in
          *state\ UP*)
            restore_dataplane_sysctl "eth1" || true
            dataplane_ignore 2
            ;;
        esac
        ;;
      *" eth2@"*|*" eth2:"*)
        case "$line" in
          *state\ UP*)
            restore_dataplane_sysctl "eth2" || true
            dataplane_ignore 2
            ;;
        esac
        ;;
      *" eth3@"*|*" eth3:"*)
        case "$line" in
          *state\ UP*)
            restore_dataplane_sysctl "eth3" || true
            dataplane_ignore 2
            ;;
        esac
        ;;
      *" eth4@"*|*" eth4:"*)
        case "$line" in
          *state\ UP*)
            restore_dataplane_sysctl "eth4" || true
            dataplane_ignore 2
            ;;
        esac
        ;;
    esac
  done
) &
wait
