#!/bin/bash
# x1 — FRR initialize (generated by xForm semantic-lab-fw)
set -e
set -x
#
# Create bash profile script
#
cat <<'SCRIPT' >/root/.bash_profile
#!/bin/bash
#
export PS1="\h(bash)# "
echo
echo "Use vtysh to connect to FRR daemon"
echo
SCRIPT
#
# Forwarding (also set via vtysh below; set early for data-plane interfaces)
#
sysctl -w net.ipv4.ip_forward=1
sysctl -w net.ipv6.conf.all.forwarding=1
#
# Management VRF — move eth0 into mgmt so data-plane routing stays separate
#
if grep vrf /proc/modules && ip link show dev eth0; then
  def_nh=$(ip route list default|awk '{ print $3 }')
  if [ ! -e /sys/devices/virtual/net/mgmt ]; then
    ip link add mgmt type vrf table 42
  fi
  ip link set mgmt up
  sysctl -qw net.ipv6.conf.eth0.keep_addr_on_down=1
  ip link set eth0 master mgmt
  if [[ -n "$def_nh" ]]; then
    ip route add 0.0.0.0/0 vrf mgmt via $def_nh
  fi
fi
#
# Send ARP requests from a sane source IP address
#
sysctl -w net.ipv4.conf.all.arp_announce=2
#
# Create missing loopback/stub as dummy (do NOT create ethN — Containerlab attaches those)
#
#
# Wait for Containerlab data-plane interfaces before sysctl / addressing
#
for _ in $(seq 1 50); do
  [ -e /sys/class/net/lo ] && break
  sleep 0.1
done
[ -e /sys/class/net/lo ] || { echo "interface lo not present"; exit 1; }
for _ in $(seq 1 50); do
  [ -e /sys/class/net/eth1 ] && break
  sleep 0.1
done
[ -e /sys/class/net/eth1 ] || { echo "interface eth1 not present"; exit 1; }
#
# Linux interface sysctl: disable IPv6 on IPv4-only interfaces, then up
#
ip link set lo down
sysctl -qw net/ipv6/conf/lo/disable_ipv6=1
ip link set lo up
ip link set eth1 down
sysctl -qw net/ipv6/conf/eth1/disable_ipv6=1
ip link set eth1 up
#
# FRR daemons — baseline all optional daemons off; modules enable what they need
#
cat >/etc/frr/daemons <<'DAEMONS'
# Generated by xForm semantic-lab-fw (Netlab-style FRR daemons)
bgpd=no
ospfd=no
ospf6d=no
ripd=no
ripngd=no
isisd=no
pimd=no
ldpd=no
nhrpd=no
eigrpd=no
babeld=no
sharpd=no
pbrd=no
bfdd=no
fabricd=no
vrrpd=no
pathd=no
vtysh_enable=yes
zebra_options="  -A 127.0.0.1 -s 90000000"
bgpd_options="   -A 127.0.0.1"
ospfd_options="  -A 127.0.0.1"
ospf6d_options=" -A ::1"
ripd_options="   -A 127.0.0.1"
ripngd_options=" -A ::1"
isisd_options="  -A 127.0.0.1"
pimd_options="   -A 127.0.0.1"
ldpd_options="   -A 127.0.0.1"
nhrpd_options="  -A 127.0.0.1"
eigrpd_options=" -A 127.0.0.1"
babeld_options=" -A 127.0.0.1"
sharpd_options=" -A 127.0.0.1"
pbrd_options="   -A 127.0.0.1"
staticd_options="-A 127.0.0.1"
bfdd_options="   -A 127.0.0.1"
fabricd_options="-A 127.0.0.1"
vrrpd_options="  -A 127.0.0.1"
pathd_options="  -A 127.0.0.1"
frr_profile="datacenter"
bgpd=yes
DAEMONS
#
# vtysh + log directory
#
echo "service integrated-vtysh-config" >/etc/frr/vtysh.conf
mkdir -p /var/log/frr && chown frr:frr /var/log/frr
#
# Initial FRR config applied via vtysh after daemons are up
#
cat >/tmp/config <<'CONFIG'
hostname x1
!
log file /var/log/frr/frr.log informational
!
ip forwarding
ipv6 forwarding
!
vrf mgmt
 exit-vrf
!
frr defaults datacenter
!
interface lo
 no shutdown
 ip address 10.0.0.2/32
!
interface eth1
 no shutdown
 ip address 10.1.0.2/30
!
do write
CONFIG
#
# Start FRR (reads /etc/frr/daemons), wait for settle, apply initial config
#
/usr/lib/frr/docker-start &
sleep 1
vtysh -f /tmp/config
wait
